### ISSUE TITLE
Package resolution error with latest release release 3.7.4

### ISSUE THREAD

**Issue by astreube** [zeroc-ice/ice-spm#1]
The master branch has a package resolution error since the update to Ice 3.7.4. See attached screenshot for details.

<img width="730" alt="Bildschirmfoto 2020-07-01 um 15 48 24" src="https://user-images.githubusercontent.com/3835925/86252285-4dfa2280-bbb3-11ea-8174-53cc6c8e3710.png">

**Comment by externl** [comment]
Hi @astreube, thanks for notifying us. This should be resolved now.
